Info<< "\nConstructing reacting cloud1" << endl;
basicReactingTypeCloud parcels1
(
    "reactingCloud1",
    rho,
    U,
    g,
    slgThermo
);

Info<< "\nConstructing reacting cloud2" << endl;
basicReactingTypeCloud parcels2
(
    "reactingCloud2",
    rho,
    U,
    g,
    slgThermo
);

Info<< "\nConstructing reacting cloud3" << endl;
basicReactingTypeCloud parcels3
(
    "reactingCloud3",
    rho,
    U,
    g,
    slgThermo
);

Info<< "\nConstructing reacting cloud4" << endl;
basicReactingTypeCloud parcels4
(
    "reactingCloud4",
    rho,
    U,
    g,
    slgThermo
);
